import React from 'react'
import EmailCapture from '../components/EmailCapture';
import Link from 'next/link';

export const metadata = {
  title: "ffwefwfwfwe",
  description: "Generated by create next app",
};

export default function Menu() {
  return (
    <div className='menu'>
      <div className='menu-cover' >
        <div className='menu-cover-texts'>
          <h1 className='indie-flower'>Enjoy the pure bite</h1>
          <p>
            is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.
          </p>
        </div>
        <div className='menu-btns'>
          <button className='menu-selected'>
            All
          </button>
        </div>  
      </div>

      <EmailCapture />
    </div>
  )
}
