import React from 'react'
import EmailCapture from '../components/EmailCapture';
import Link from 'next/link';
import FetchCakes from '../FetchCakes';

export const metadata = {
  title: "Hanzo's Cakery | Menu",
  description: "Generated by create next app",
};

export default function Menu() {
  return (
    <div className='menu'>
      <div className='menu-cover' >
        <div className='menu-cover-texts'>
          <h1 className='indie-flower'>Enjoy the pure bite</h1>
          <p>
            is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.
          </p>
        </div>
        <div className='menu-btns'>
          <button className='menu-selected'>
            All
          </button>
        </div>  
      </div>

      <div className='grid-3 menu-menus'> 

      <FetchCakes />
        
      {/* <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div> */}


      </div>

      <EmailCapture />
    </div>
  )
}
