import React from 'react'
import EmailCapture from '../components/EmailCapture';
import Link from 'next/link';

export const metadata = {
  title: "Hanzo's Cakery | Menu",
  description: "Generated by create next app",
};

export default function Menu() {
  return (
    <div className='menu'>
      <div className='menu-cover' >
        <div className='menu-cover-texts'>
          <h1 className='indie-flower'>Enjoy the pure bite</h1>
          <p>
            is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.
          </p>
        </div>
        <div className='menu-btns'>
          <button className='menu-selected'>
            All
          </button>
        </div>  
      </div>

      <div className='grid-3 menu-menus'> 
        
      <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="https://scontent.fcgy2-1.fna.fbcdn.net/v/t39.30808-6/418443456_327620643436046_6191546965866612978_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=dd5e9f&_nc_ohc=hF7JYgkzMeoAX8xnPsS&_nc_ht=scontent.fcgy2-1.fna&oh=00_AfB5IKhi2rbWhb6wZYV0j1eFo4FAyIIRae_n5zzXco88ew&oe=65CFE267" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>
        <div className="homepage-cake-card"> 
            <div className="cake-card-cover"> 
              <img className="cake-card-cover-img" src="/imgs/blob-cake-1.png" />
            </div>
            <div className="cake-card-body">
              <h5 className="cake-card-header">
                Focaccia
              </h5>

              <span className="cake-card-price">
                ₱ 350
              </span>

              <p className="cake-card-p">
                Top with chocolate buttercream and chocolate chips for 3x the chocolate flavor.
              </p>
            </div>
        </div>


      </div>

      <EmailCapture />
    </div>
  )
}
